# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setEnabled(True)
        MainForm.resize(241, 380)
        palette = QtGui.QPalette()
        MainForm.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Carlito")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        MainForm.setFont(font)
        MainForm.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainForm.setWindowIcon(icon)
        MainForm.setStyleSheet("")
        self.result_show = QtWidgets.QLabel(MainForm)
        self.result_show.setGeometry(QtCore.QRect(0, 0, 232, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 202, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 202, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 202, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.result_show.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.result_show.setFont(font)
        self.result_show.setStyleSheet("")
        self.result_show.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_show.setFrameShadow(QtWidgets.QFrame.Plain)
        self.result_show.setLineWidth(0)
        self.result_show.setMidLineWidth(0)
        self.result_show.setText("")
        self.result_show.setTextFormat(QtCore.Qt.AutoText)
        self.result_show.setScaledContents(False)
        self.result_show.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_show.setObjectName("result_show")
        self.pushButton_ac = QtWidgets.QPushButton(MainForm)
        self.pushButton_ac.setGeometry(QtCore.QRect(0, 80, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_ac.setFont(font)
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.pushButton_plus_minus = QtWidgets.QPushButton(MainForm)
        self.pushButton_plus_minus.setGeometry(QtCore.QRect(120, 80, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_plus_minus.setFont(font)
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.pushButton_delit = QtWidgets.QPushButton(MainForm)
        self.pushButton_delit.setGeometry(QtCore.QRect(180, 80, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_delit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_delit.setFont(font)
        self.pushButton_delit.setStyleSheet("")
        self.pushButton_delit.setAutoDefault(False)
        self.pushButton_delit.setDefault(False)
        self.pushButton_delit.setFlat(False)
        self.pushButton_delit.setObjectName("pushButton_delit")
        self.pushButton_8 = QtWidgets.QPushButton(MainForm)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 140, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(MainForm)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 140, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_x = QtWidgets.QPushButton(MainForm)
        self.pushButton_x.setGeometry(QtCore.QRect(180, 140, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_x.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_x.setFont(font)
        self.pushButton_x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_x.setStyleSheet("")
        self.pushButton_x.setCheckable(False)
        self.pushButton_x.setAutoRepeat(False)
        self.pushButton_x.setAutoDefault(False)
        self.pushButton_x.setDefault(False)
        self.pushButton_x.setFlat(False)
        self.pushButton_x.setObjectName("pushButton_x")
        self.pushButton_9 = QtWidgets.QPushButton(MainForm)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 140, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_5 = QtWidgets.QPushButton(MainForm)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(MainForm)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_minus = QtWidgets.QPushButton(MainForm)
        self.pushButton_minus.setGeometry(QtCore.QRect(180, 200, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_minus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("")
        self.pushButton_minus.setAutoDefault(False)
        self.pushButton_minus.setDefault(False)
        self.pushButton_minus.setFlat(False)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_6 = QtWidgets.QPushButton(MainForm)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(MainForm)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 260, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(MainForm)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 260, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_plus = QtWidgets.QPushButton(MainForm)
        self.pushButton_plus.setGeometry(QtCore.QRect(180, 260, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_plus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("")
        self.pushButton_plus.setAutoDefault(False)
        self.pushButton_plus.setDefault(False)
        self.pushButton_plus.setFlat(False)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_3 = QtWidgets.QPushButton(MainForm)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 260, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_0 = QtWidgets.QPushButton(MainForm)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 320, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_ravno = QtWidgets.QPushButton(MainForm)
        self.pushButton_ravno.setGeometry(QtCore.QRect(180, 320, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 214, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_ravno.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_ravno.setFont(font)
        self.pushButton_ravno.setStyleSheet("")
        self.pushButton_ravno.setAutoDefault(False)
        self.pushButton_ravno.setDefault(False)
        self.pushButton_ravno.setFlat(False)
        self.pushButton_ravno.setObjectName("pushButton_ravno")
        self.pushButton_dot = QtWidgets.QPushButton(MainForm)
        self.pushButton_dot.setGeometry(QtCore.QRect(120, 320, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_clear = QtWidgets.QPushButton(MainForm)
        self.pushButton_clear.setGeometry(QtCore.QRect(60, 320, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(22)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Калькулятор"))
        self.pushButton_ac.setText(_translate("MainForm", "AC"))
        self.pushButton_plus_minus.setText(_translate("MainForm", "+/-"))
        self.pushButton_delit.setText(_translate("MainForm", "/"))
        self.pushButton_8.setText(_translate("MainForm", "8"))
        self.pushButton_7.setText(_translate("MainForm", "7"))
        self.pushButton_x.setText(_translate("MainForm", "x"))
        self.pushButton_9.setText(_translate("MainForm", "9"))
        self.pushButton_5.setText(_translate("MainForm", "5"))
        self.pushButton_4.setText(_translate("MainForm", "4"))
        self.pushButton_minus.setText(_translate("MainForm", "-"))
        self.pushButton_6.setText(_translate("MainForm", "6"))
        self.pushButton_2.setText(_translate("MainForm", "2"))
        self.pushButton_1.setText(_translate("MainForm", "1"))
        self.pushButton_plus.setText(_translate("MainForm", "+"))
        self.pushButton_3.setText(_translate("MainForm", "3"))
        self.pushButton_0.setText(_translate("MainForm", "0"))
        self.pushButton_ravno.setText(_translate("MainForm", "="))
        self.pushButton_dot.setText(_translate("MainForm", "."))
        self.pushButton_clear.setText(_translate("MainForm", "<"))

